monolog:
  channels:
    - deprecation
when@dev:
  monolog:
    handlers:
      file:
        type: stream
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        level: info
        formatter: monolog.formatter.json
        buffer_size: 150
        channels: null
      console:
        type: console
        path: 'php://stderr'
        level: info
        formatter: monolog.formatter.json
        channels: null
