nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000','https://goodshi.fr']
        allow_methods: ['POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
    paths:
        '^/contact':
            allow_origin: ['http://localhost:3000','https://goodshi.fr']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
