nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_methods: ['POST', 'OPTIONS']
        allow_headers: ['Content-Type', Authorization']
        allow_credentials: true
    paths:
        '^/contact':
            allow_origin: ['http://localhost:3000']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', Authorization']
            allow_credentials: true
